/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BiasCategory { 'count' : bigint, 'category' : string }
export interface ConversationPattern {
  'topic' : string,
  'emotion' : string,
  'speakerRole' : string,
  'occurrence' : bigint,
  'intent' : string,
}
export interface EthicalViolation { 'count' : bigint, 'violationType' : string }
export interface ExtendedConversationSession {
  'biasLog' : Array<BiasCategory>,
  'patterns' : Array<ConversationPattern>,
  'owner' : Principal,
  'transcriptEntries' : Array<TranscriptEntry>,
  'timestamp' : Time,
  'rawTranscript' : string,
  'sessionId' : string,
  'ethicalViolations' : Array<EthicalViolation>,
}
export type Time = bigint;
export interface TranscriptEntry {
  'text' : string,
  'detectedLanguage' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create session with ethics checks (users only)
   */
  'createSession' : ActorMethod<
    [string, string, Array<TranscriptEntry>],
    ExtendedConversationSession
  >,
  /**
   * / Delete session (owner only)
   */
  'deleteSession' : ActorMethod<[string], undefined>,
  /**
   * / Get aggregate data for the caller's sessions (admins see all)
   */
  'getAggregateData' : ActorMethod<
    [],
    {
      'patterns' : Array<ConversationPattern>,
      'ethicalViolations' : Array<EthicalViolation>,
      'biases' : Array<BiasCategory>,
    }
  >,
  /**
   * / Admin-only: get all bias logs across all sessions for operator review
   */
  'getAllBiasLogs' : ActorMethod<[], Array<[string, Array<BiasCategory>]>>,
  /**
   * / Admin-only: get all ethical violation logs across all sessions for operator review
   */
  'getAllEthicalViolationLogs' : ActorMethod<
    [],
    Array<[string, Array<EthicalViolation>]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get a specific session by ID (owner or admin only)
   */
  'getSession' : ActorMethod<[string], ExtendedConversationSession>,
  /**
   * / Get all sessions belonging to the caller (admins see all sessions)
   */
  'getSessionsByTimestamp' : ActorMethod<
    [],
    Array<ExtendedConversationSession>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Update session transcript and patterns (owner only)
   */
  'updateSession' : ActorMethod<
    [string, string, Array<TranscriptEntry>, Array<ConversationPattern>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];