/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TranscriptEntry = IDL.Record({
  'text' : IDL.Text,
  'detectedLanguage' : IDL.Text,
});
export const BiasCategory = IDL.Record({
  'count' : IDL.Nat,
  'category' : IDL.Text,
});
export const ConversationPattern = IDL.Record({
  'topic' : IDL.Text,
  'emotion' : IDL.Text,
  'speakerRole' : IDL.Text,
  'occurrence' : IDL.Nat,
  'intent' : IDL.Text,
});
export const Time = IDL.Int;
export const EthicalViolation = IDL.Record({
  'count' : IDL.Nat,
  'violationType' : IDL.Text,
});
export const ExtendedConversationSession = IDL.Record({
  'biasLog' : IDL.Vec(BiasCategory),
  'patterns' : IDL.Vec(ConversationPattern),
  'owner' : IDL.Principal,
  'transcriptEntries' : IDL.Vec(TranscriptEntry),
  'timestamp' : Time,
  'rawTranscript' : IDL.Text,
  'sessionId' : IDL.Text,
  'ethicalViolations' : IDL.Vec(EthicalViolation),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(TranscriptEntry)],
      [ExtendedConversationSession],
      [],
    ),
  'deleteSession' : IDL.Func([IDL.Text], [], []),
  'getAggregateData' : IDL.Func(
      [],
      [
        IDL.Record({
          'patterns' : IDL.Vec(ConversationPattern),
          'ethicalViolations' : IDL.Vec(EthicalViolation),
          'biases' : IDL.Vec(BiasCategory),
        }),
      ],
      ['query'],
    ),
  'getAllBiasLogs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(BiasCategory)))],
      ['query'],
    ),
  'getAllEthicalViolationLogs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(EthicalViolation)))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSession' : IDL.Func([IDL.Text], [ExtendedConversationSession], ['query']),
  'getSessionsByTimestamp' : IDL.Func(
      [],
      [IDL.Vec(ExtendedConversationSession)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateSession' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(TranscriptEntry),
        IDL.Vec(ConversationPattern),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TranscriptEntry = IDL.Record({
    'text' : IDL.Text,
    'detectedLanguage' : IDL.Text,
  });
  const BiasCategory = IDL.Record({ 'count' : IDL.Nat, 'category' : IDL.Text });
  const ConversationPattern = IDL.Record({
    'topic' : IDL.Text,
    'emotion' : IDL.Text,
    'speakerRole' : IDL.Text,
    'occurrence' : IDL.Nat,
    'intent' : IDL.Text,
  });
  const Time = IDL.Int;
  const EthicalViolation = IDL.Record({
    'count' : IDL.Nat,
    'violationType' : IDL.Text,
  });
  const ExtendedConversationSession = IDL.Record({
    'biasLog' : IDL.Vec(BiasCategory),
    'patterns' : IDL.Vec(ConversationPattern),
    'owner' : IDL.Principal,
    'transcriptEntries' : IDL.Vec(TranscriptEntry),
    'timestamp' : Time,
    'rawTranscript' : IDL.Text,
    'sessionId' : IDL.Text,
    'ethicalViolations' : IDL.Vec(EthicalViolation),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(TranscriptEntry)],
        [ExtendedConversationSession],
        [],
      ),
    'deleteSession' : IDL.Func([IDL.Text], [], []),
    'getAggregateData' : IDL.Func(
        [],
        [
          IDL.Record({
            'patterns' : IDL.Vec(ConversationPattern),
            'ethicalViolations' : IDL.Vec(EthicalViolation),
            'biases' : IDL.Vec(BiasCategory),
          }),
        ],
        ['query'],
      ),
    'getAllBiasLogs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(BiasCategory)))],
        ['query'],
      ),
    'getAllEthicalViolationLogs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(EthicalViolation)))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSession' : IDL.Func(
        [IDL.Text],
        [ExtendedConversationSession],
        ['query'],
      ),
    'getSessionsByTimestamp' : IDL.Func(
        [],
        [IDL.Vec(ExtendedConversationSession)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateSession' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(TranscriptEntry),
          IDL.Vec(ConversationPattern),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };